# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gymx import env_pb2 as gymx_dot_env__pb2


class EnvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Make = channel.unary_unary(
        '/Env/Make',
        request_serializer=gymx_dot_env__pb2.Name.SerializeToString,
        response_deserializer=gymx_dot_env__pb2.Info.FromString,
        )
    self.Reset = channel.unary_unary(
        '/Env/Reset',
        request_serializer=gymx_dot_env__pb2.Empty.SerializeToString,
        response_deserializer=gymx_dot_env__pb2.Observation.FromString,
        )
    self.Step = channel.unary_unary(
        '/Env/Step',
        request_serializer=gymx_dot_env__pb2.Action.SerializeToString,
        response_deserializer=gymx_dot_env__pb2.Transition.FromString,
        )


class EnvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Make(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Step(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EnvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Make': grpc.unary_unary_rpc_method_handler(
          servicer.Make,
          request_deserializer=gymx_dot_env__pb2.Name.FromString,
          response_serializer=gymx_dot_env__pb2.Info.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=gymx_dot_env__pb2.Empty.FromString,
          response_serializer=gymx_dot_env__pb2.Observation.SerializeToString,
      ),
      'Step': grpc.unary_unary_rpc_method_handler(
          servicer.Step,
          request_deserializer=gymx_dot_env__pb2.Action.FromString,
          response_serializer=gymx_dot_env__pb2.Transition.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Env', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
